apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus_ds
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    uid: loki_ds
    type: loki
    access: proxy
    url: http://loki:3100

  - name: Tempo
    uid: tempo_ds
    type: tempo
    access: proxy
    url: http://tempo:3200
